mod catchup;
mod config;
pub(crate) mod cross_surface_hybrid;
mod document;
mod embedding;
mod endpoint;
mod fusion;
mod hydration;
mod lifecycle;
mod search;
mod search_filtered;
pub(crate) mod support;
pub(crate) mod sync;
